apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /usr/local/bin/kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zenoss4-rsyslog
  name: zenoss4-rsyslog
spec:
  type: "NodePort"
  ports:
  - name: "514"
    protocol: UDP
    port: 514
    nodePort: 30514
  selector:
    io.kompose.service: zenoss4-core
status:
  loadBalancer: {}
