kind: ConfigMap
apiVersion: v1
metadata:
  name: zenoss4-mariadb-config
  namespace: monitoring
data:
  20_innodb.cnf: |2
    [mysqld]
    ## INNODB settings
    #innodb_force_recovery=4
    innodb_open_files = 500
    innodb_file_per_table = 1
    innodb_use_native_aio = 1
    innodb_doublewrite = 0
    innodb_change_buffering = inserts
    innodb_io_capacity = 999999999
    innodb_show_verbose_locks = 1
    innodb_show_locks_held = 1
    innodb_old_blocks_time = 0
    innodb_old_blocks_pct = 37
    innodb_autoinc_lock_mode = 2
    #innodb_buffer_pool_size = 8G
    innodb_buffer_pool_size = 256M
    innodb_additional_mem_pool_size=20M
    #innodb_buffer_pool_instances = 3
    innodb_buffer_pool_instances = 2
    innodb_data_file_path = ibdata1:10M:autoextend
    #innodb_write_io_threads = 8
    innodb_write_io_threads = 1
    #innodb_read_io_threads = 8
    innodb_read_io_threads = 1
    innodb_thread_concurrency = 0
    innodb_flush_log_at_trx_commit = 1
    innodb_log_buffer_size = 8M
    innodb_log_file_size = 512M
    innodb_log_files_in_group = 2
    innodb_max_dirty_pages_pct = 90
    innodb_flush_method = O_DSYNC ## ghosts O_DSYNC, normal O_DIRECT
    innodb_lock_wait_timeout = 600
    innodb_use_sys_malloc = 1

  10_mysqld.cnf: |2
    [mysqld]
    ## General settings
    user = mysql
    port = 3306
    bind-address = 0.0.0.0
    #datadir = /opt/mysql
    #tmpdir = /run/mysqld
    #socket = /opt/mysql/mysql.sock
    #pid_file = /opt/mysql/mysql.pid
    log-error = /var/log/mysqld.log
    #binlog_format = ROW
    #log_bin = /var/log/mysql/mariadb-bin
    symbolic-links = 0
    #event_scheduler = 1
    lower_case_table_names = 0
    expire_logs_days = 3
    interactive_timeout = 20
    back_log = 75
    table_cache = 60000
    thread_cache=32
    #wait_timeout = 300 ## 5min
    wait_timeout = 1800 ## 30min
    connect_timeout = 10
    query_cache_strip_comments = 1
    max_connections = 20000
    max_connect_errors = 10000
    open_files_limit = 65535
    table_definition_cache = 5120
    table_open_cache = 10240
    max_allowed_packet = 128M
    binlog_cache_size = 8M
    max_heap_table_size = 128M
    read_buffer_size = 8M
    read_rnd_buffer_size = 16M
    sort_buffer_size = 16M
    join_buffer_size = 16M
    thread_cache_size = 16
    #thread_concurrency = 16
    query_cache_size = 1024M ## def. 64M
    query_cache_limit = 64M ## def. 2M
    ft_min_word_len = 4
    default_storage_engine = innodb
    thread_stack = 256K
    transaction_isolation = READ-COMMITTED
    tmp_table_size = 256M
    max_sp_recursion_depth = 50
     
  60_mysqld_safe.cnf: |2
    [mysqld_safe]
    open-files-limit = 8192
    skip_log_error
    syslog

