apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zenoss4-core-optzenossperf
  name: zenoss4-core-optzenossperf
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
status: {}
